.\" bdf2amiga 1.3--BDF to Amiga font converter
.\" Copyright © 1998 Kriton Kyrimis
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\" 
.TH bdf2amiga 1 "20 Aug 1998" "Kriton Kyrimis"
.SH NAME
bdf2amiga \- converts BDF fonts to Amiga assembly format
.SH SYNOPSIS
.B bdf2amiga
[-d OutputDirectory] [-f FamilyName] [-h] [-i] [-v] BDFfile
.SH DESCRIPTION
This program converts X11 fonts in BDF format to Amiga assembly, which can
then be assembled and linked on an Amiga to generate Amiga bitmapped fonts.
The generated assembly is saved in a file whose name is formed by
concatenating the family name of the font (e.g., Times), its point size, and,
if the font is bold or italic, the letters
.I i
and/or
.IR b ,
as appropriate, and with extension
.I .a.
E.g., for a Times font with size 12, the generated assembly file will be
called
.IR Times12.a .
.SH OPTIONS
.TP
.B -d OutputDirectory
This option specifies the directory where the generated assembly file will be
created.
The default is the current directory.
.TP
.B -f FamilyName
Overrides the font family name contained in the BDF file with
.IR FamilyName .
As the font family name is used to form the name of the output file, this
option is useful for fonts that do not contain their family name in the BDF
file.
.TP
.I -h
Displays a short help message.
.TP
.I -i
Instructs
.I bdf2amiga
not to generate references to Amiga header files, generating EQU directives
for the symbols required by the generated code.
This is not safe, as the information in these header files may change in the
future.
Thus, you should only use this option
if you do not have access to the header files.
.TP
.I -v
Displays the program version.
.SH REQUIREMENTS
.IP \(bu 2
X11 fonts in BDF format.
An excellent source for such fonts, and the reason
that this program was written, is the FreeType package
.nf
(http://www.physiol.med.tu-muenchen.de/~robert/freetype.html),
.fi
a TrueType engine which comes with a font previewer for the Amiga and
a TrueType to BDF conversion utility.
(The latter is contained in the ``full'' distribution package.)
.IP \(bu 2
An assembler.
I have used a68k successfully.
.IP \(bu 2
A linker.
I have used slink, but blink should work just as well.
.SH EXAMPLE
Let us say that you want to convert a font called FancyFont12.bdf to Amiga
format.
This can be done with the following steps:
.IP 1. 3
Convert the font to Amiga assembly code using
.IR bdf2amiga :
.br
.RS
bdf2amiga FancyFont12.bdf
.RE
This will create a file called something like FancyFont15.a (see the bugs
section).
.IP 2. 3
Assemble the font:
.RS
a68k -iinclude: FancyFont15.a
.RE
This will generate FancyFont15.o.
.IP 3. 3
Link the font:
.RS
blink from FancyFont15.o to 15
.br
or
.br
slink from FancyFont15.o to 15 noicons
.br
depending on which linker you use.
.RE
This will generate file 15, which is the font in Amiga format.
.IP 4. 3
Create a directory named FancyFont in the FONTS: directory, and put file 15
there.
Run fixfonts to generate FONTS:FancyFont.font and to make the font available
to your Amiga.
(If you are converting many fonts, you need only run fixfonts once,
after all the fonts have been converted.)
.SH AUTHOR
Kriton Kyrimis <kyrimis@cti.gr>
.SH BUGS
On the Amiga, the size of a font is its vertical size in pixels, and not its
point size, which is a rough measure of the width of the font's characters.
As X11 font size is point size, this has the result that the size of the
generated font is different from the original.
.P
This program has been tested mainly with fonts generated by the
.I ttf2bdf
program that comes with the FreeType package, and only briefly tested with
other fonts.
If you add to this that, since I didn't have any documentation on
the BDF format, I had to guess its structure by staring at sample fonts, 
finding a font that breaks
.I bdf2amiga
should not be very difficult.
Let me know, and I'll see if I can provide a fix.
.SH 
